# Generated by Django 3.2.1 on 2021-05-15 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productcategory',
            fields=[
                ('category_num', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Enter category name', max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_num', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Enter product name', max_length=50, verbose_name='Produce name')),
                ('product_price', models.FloatField(help_text='Enter product price', verbose_name='product price')),
                ('product_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('bill_num', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField()),
                ('products', models.ManyToManyField(null=True, to='helloworld.product')),
            ],
        ),
    ]
