# Generated by Django 3.2.1 on 2021-05-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_cat',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='productcategory',
        ),
    ]
