# Generated by Django 3.2.1 on 2021-05-24 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helloworld', '0002_auto_20210516_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='productcategory',
            fields=[
                ('category_num', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Enter category name', max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_num', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Enter product name', max_length=50, verbose_name='Product name')),
                ('product_price', models.FloatField()),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('bill_num', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Enter customer name', max_length=50, verbose_name='Customer name')),
                ('total_sum', models.FloatField()),
                ('products', models.ManyToManyField(to='helloworld.product')),
            ],
        ),
    ]
