# Generated by Django 3.2.1 on 2021-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_bill_product_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_sum',
            field=models.FloatField(default=2.0),
        ),
    ]
