# Generated by Django 3.2.1 on 2021-07-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_alter_bill_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products',
        ),
        migrations.CreateModel(
            name='bill_products',
            fields=[
                ('bill_pronum', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='Default is one')),
                ('bill_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='product',
            field=models.ManyToManyField(to='helloworld.bill_products'),
        ),
    ]
