# Generated by Django 3.2.1 on 2021-07-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_auto_20210718_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_products',
            name='bill_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helloworld.bill'),
        ),
    ]
